### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by dschwoerer**

### CODE REVIEW

**Comment by ZedThree** [comment]
Please could you also bump `python_requires` in `setup.cfg`?

**Comment by dschwoerer** [comment]
It seems the set of required tests needs to be updated - github's repo settings maybe?

**Comment by dschwoerer** [comment]
Any idea why the tests time out now?

It cannot be related to the change?

**Comment by ZedThree** [comment]
No, looking back through previous Action runs, something made them jump up to 6h!

**Comment by ZedThree** [comment]
This is the last successful run, across all branches, and it took under an hour: https://github.com/boutproject/xBOUT/actions/runs/3135003875
That's commit 1e132422dcc80dcad2972f59f547a5ae2cf64626

**Comment by dschwoerer** [comment]
both xarray and dask where updated to 2022.10.0

**Comment by dschwoerer** [comment]
I have started runs to debug:

old dask: https://github.com/boutproject/xBOUT/actions/runs/3271985035

old xarray: https://github.com/boutproject/xBOUT/actions/runs/3271980130

**Comment by ZedThree** [comment]
Yeah, I just checked locally, upgrading to those versions is a _massive_ slowdown

**Comment by dschwoerer** [comment]
Reported as https://github.com/pydata/xarray/issues/7181

**Comment by ZedThree** [comment]
I wondered if it got stuck on the last few tests perhaps and ran `pytest -k plot -vv --long`. They completed in about 6 minutes. Upgrading xarray and dask from 2022.06/07 (respectively) to 2022.10 and the same tests took a _lot_ longer -- 18% done in 30 minutes.

I've not checked any others yet, but I'll run with `--profile` now and see if that gives any insight

**Comment by johnomotani** [comment]
It seems to be xarray rather than dask - I ran `pytest` with dask==2022.10.0 and xarray==2022.6.0 and tests took about the same time as with my original versions (even a few seconds quicker).

**Comment by johnomotani** [comment]
Problem seems to be in `interpolate_parallel()` - if I run `time pytest -k "not test_interpolate_parallel" -v`, the tests all pass in a reasonable time.

**Comment by ZedThree** [comment]
See https://github.com/pydata/xarray/issues/7181#issuecomment-1282216041 for a bit more detail -- it seems it's basically all coming from copying arrays. Are we copying too much and/or in the wrong places?

**Comment by ZedThree** [comment]
combined

**Comment by johnomotani** [comment]
> Problem seems to be in `interpolate_parallel()` - if I run `time pytest -k "not test_interpolate_parallel" -v`, the tests all pass in a reasonable time.

Sorry, ignore that - I just used the wrong conda environment. All the stuff is slow :disappointed:

**Comment by ZedThree** [comment]
From what I can tell, the proximate cause is `region:1713:_from_region`: it does a lot of copying, and copying suddenly got a _lot_ more expensive in 2022.10.

It looks like this is also a substantial part of the runtime even with xarray 2022.06, so it's probably worth trying to optimise it anyway.

**Comment by johnomotani** [comment]
The regions stuff I was never super-happy with from a performance point of view. Possible optimisation:
* It might be possible to join together the `concat`s here into 2, concatenating guard cells from both sides at once onto the main grid (or maybe even just one, but I'm not sure xarray supports a not-really structured `concat`), that might reduce the number of copies.
    https://github.com/boutproject/xBOUT/blob/a23da818042ab49911d34c0f0cb37a0a1731dd45/xbout/region.py#L1738-L1745
* The nuclear option would be to completely restructure xBOUT so everything is loaded/handled in separate regions, and doesn't have to do any splitting/recombining. I'm not 100% sure that's a good idea if someone offered to do it for free, but am pretty sure it's not worth the time it would take!
* I'm not sure if it would work, but it might be possible to reduce the number of regions the data is split up into. There are never branch cuts in the x-direction, so maybe for example the whole divertor leg could be one region, rather than the current 2 or 3. This would make getting the guard cells more complicated at branch cuts though...

**Comment by dschwoerer** [comment]
Just switch to FCI - avoid the separate regions all together :-)

Can we merge this in the mean time, so I can include this in the other PRs, to make sure they don't break the tests?

**Review by ZedThree — APPROVED** [review]

**Pull request merged**
