### PR TITLE
Packaging update, auto-publish to PyPi

### LINKED ISSUE #153: Missing dependencies?
I know that is not listed as recommended install option, but imho it should still work ...

```
👍 pip install --user git+https://github.com/boutproject/xBOUT.git
Collecting git+https://github.com/boutproject/xBOUT.git
  Cloning https://github.com/boutproject/xBOUT.git to /tmp/pip-req-build-s32ujhej
  Running command git clone -q https://github.com/boutproject/xBOUT.git /tmp/pip-req-build-s32ujhej
Collecting xarray>=0.16.0
  Downloading https://files.pythonhosted.org/packages/7a/cc/62ca520e349e63b05ce43c781757cbd3bea71d83ece96f2176763b57e8c2/xarray-0.16.1-py3-none-any.whl (720kB)
     |████████████████████████████████| 727kB 1.1MB/s 
Collecting dask[array]>=2.10.0
  Downloading https://files.pythonhosted.org/packages/e3/95/a4d8b380009e55de64ef3fa386f67fcf3e1c3c8e4eb4536c3d68b82145d5/dask-2.28.0-py3-none-any.whl (848kB)
     |████████████████████████████████| 849kB 1.8MB/s 
Collecting natsort>=5.5.0
  Downloading https://files.pythonhosted.org/packages/0f/65/81883897f4aaa1e53deaa65137318cfe80b36ce013c2e86f8fd0843cfa02/natsort-7.0.1-py3-none-any.whl
Requirement already satisfied: matplotlib>=3.1.1 in /usr/lib64/python3.8/site-packages (from xbout==0.1.0) (3.2.2)
Collecting animatplot>=0.4.1
  Downloading https://files.pythonhosted.org/packages/6f/92/5d022c6fc5157e68703aaf7259085a8ea4e27a9404ffcdff2ec33e79936c/animatplot-0.4.1.tar.gz
Requirement already satisfied: netcdf4>=1.4.0 in /usr/lib64/python3.8/site-packages (from xbout==0.1.0) (1.5.3)
Requirement already satisfied: Pillow>=6.1.0 in /usr/lib64/python3.8/site-packages (from xbout==0.1.0) (7.0.0)
Requirement already satisfied: setuptools>=38.4 in /usr/lib/python3.8/site-packages (from xarray>=0.16.0->xbout==0.1.0) (41.6.0)
Requirement already satisfied: pandas>=0.25 in /usr/lib64/python3.8/site-packages (from xarray>=0.16.0->xbout==0.1.0) (0.25.3)
Requirement already satisfied: numpy>=1.15 in /usr/lib64/python3.8/site-packages (from xarray>=0.16.0->xbout==0.1.0) (1.18.4)
Requirement already satisfied: pyyaml in /usr/lib64/python3.8/site-packages (from dask[array]>=2.10.0->xbout==0.1.0) (5.3.1)
Collecting toolz>=0.8.2; extra == "array"
  Downloading https://files.pythonhosted.org/packages/12/f5/537e55f8ba664ff2a26f26913010fb0fcb98b6bbadc6158af888184fd0b7/toolz-0.11.1-py3-none-any.whl (55kB)
     |████████████████████████████████| 61kB 2.4MB/s 
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.8/site-packages (from matplotlib>=3.1.1->xbout==0.1.0) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib64/python3.8/site-packages (from matplotlib>=3.1.1->xbout==0.1.0) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/lib/python3.8/site-packages (from matplotlib>=3.1.1->xbout==0.1.0) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3.8/site-packages (from matplotlib>=3.1.1->xbout==0.1.0) (2.8.0)
Requirement already satisfied: cftime in /usr/lib64/python3.8/site-packages (from netcdf4>=1.4.0->xbout==0.1.0) (1.0.4.2)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3.8/site-packages (from pandas>=0.25->xarray>=0.16.0->xbout==0.1.0) (2020.1)
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=3.1.1->xbout==0.1.0) (1.14.0)
Installing collected packages: xarray, toolz, dask, natsort, animatplot, xbout
  WARNING: The script natsort is installed in '/home/dave/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for animatplot ... done
    Running setup.py install for xbout ... done
Successfully installed animatplot-0.4.1 dask-2.28.0 natsort-7.0.1 toolz-0.11.1 xarray-0.16.1 xbout-0.1.0
👍 ipython
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import xbout                                                                                                                                                                                                                         
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fe6f7ed77132> in <module>
----> 1 import xbout

~/.local/lib/python3.8/site-packages/xbout/__init__.py in <module>
----> 1 from .load import open_boutdataset, collect
      2 
      3 from . import geometries
      4 from .geometries import register_geometry, REGISTERED_GEOMETRIES
      5 

~/.local/lib/python3.8/site-packages/xbout/load.py in <module>
      5 from itertools import chain
      6 
----> 7 from boutdata.data import BoutOptionsFile
      8 import xarray as xr
      9 from numpy import unique

ModuleNotFoundError: No module named 'boutdata'
```

### PR DESCRIPTION
**Pull request by johnomotani**
* Move the package setup to `pyproject.toml` and `setup.cfg` instead of `setup.py` for compatibility with PEP517 and PEP518. A stub `setup.py` is still needed for editable installs with `pip install -e .` to work.

* Add Github workflow to upload a release to PyPi when we make one.

Fixes #153

### CODE REVIEW

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
The change to `requirements.txt` is a little surprising, but it's difficult to keep up with python packaging best practices sometimes, so I assume that's fine!

You might want to also add a `.codecov.yml` to make codecov behave a bit more sensibly.

**Comment by johnomotani** [comment]
I don't remember exactly where I got that `requirements.txt` style now. Officially, `requirements.txt` is basically for pinning specific versions for a production or testing environment https://packaging.python.org/discussions/install-requires-vs-requirements/, but we take care of that by hand in the Github workflow. This blog post https://caremad.io/posts/2013/07/setup-vs-requirement/ is linked from the other article, so semi-official, and suggests a similar thing with `-e .` in `requirements.txt`.

I do prefer only maintaining one list of requirements. There are suggestions for importing `requirements.txt` in `setup.py` but I don't know if it's possible to do that in `setup.cfg`. The way I've done it means we only have to maintain the requirements in `setup.cfg`.

**Comment by ZedThree** [comment]
Thanks, that blog post cleared things up! Ok, all LGTM!

**Comment by johnomotani** [comment]
I'm thinking of going back to putting 'development requirements' in `requirements.txt`. `conda` doesn't support the `-e .` workaround and it would be nice to be able to do `conda install --file requirements.txt`.

Also, I want to add a test of `xbout.__version__` and found out that at the moment we don't get a version number unless we install xbout (i.e. just adding the git repo to `$PYTHONPATH`, xbout works but `xbout.__version__` won't exist). I think the way around this is to fall back to getting the version number directly from `setuptools_scm`, but that adds a dependency on `setuptools_scm`. If we put `setuptools_scm` in `requirements.txt` but not in `install_requires` of `setup.cfg` then it won't be installed for users (who install with pip or conda), or if you install from the repo with `pip install --user -e .`, but we can recommend developers who want to just work in the repo to do either `pip install --user -r requirements.txt` or `conda install --file requirements.txt`.

**Pull request merged**
