### PR TITLE
Fix whitespace in exception message

### PR DESCRIPTION
**Pull request by ZedThree**
Related question, is it loading a single dump file from a parallel run not supported?

### CODE REVIEW

**Comment by johnomotani** [comment]
There's a workaround here https://github.com/boutproject/xBOUT/blob/e9dc174eb3c6cff9873ca4af65c6e285d4c5c103/xbout/load.py#L388-L406 to detect if there's a single output file (e.g. from parallel output, or from having squashed the output into a single file). It also works (I use it routinely) with a set of files containing consecutive time-chunks of a run, but with the spatial domain squashed. It feels a bit hacky to me, so more elegant suggestions welcome, but works (at least for what I've wanted it for).

**Comment by johnomotani** [comment]
Related to the fixing whitespace, I'd be in favour of running `black` over the whole project, also fixing anything `flake8` complains about, and then adding them to the CI tests. Maybe we could merge #107, #108, #117 and this PR, and then have a one-shot update of the formatting?

**Comment by ZedThree** [comment]
I did run `black` on this file, and was a bit surprised to find lots of changes! I thought `black` was getting run automatically already. Am I getting mixed up with hypnotoad maybe?

**Comment by ZedThree** [comment]
Oh, sorry, the whitespace fixed here is inside the string, so wouldn't be touched by `black`. The printed error looked like:

```
ValueError: Each run directory does not contain an equal numberof output files. If the parallelization scheme of your simulation changed partway-through, then pleaseload each directory separately and concatenate themalong the time dimension with xarray.concat().
```

**Comment by johnomotani** [comment]
> I did run black on this file, and was a bit surprised to find lots of changes! I thought black was getting run automatically already. Am I getting mixed up with hypnotoad maybe?

Maybe! hypnotoad does have auto-checking with `black`, `xBOUT` does not (yet).

**Pull request merged**
